const {JSDOM,VirtualConsole}=require('jsdom');
const fs=require('fs'), assert=require('node:assert/strict');
const errors=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(fs.readFileSync('storage/app/measurement-library-qa.html','utf8'),{url:'http://localhost/measurements',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.matchMedia=()=>({matches:false,addEventListener(){}});w.fetch=()=>new Promise(()=>{});w.scrollTo=()=>{};}});
dom.window.addEventListener('load',async()=>{try{
 const w=dom.window;
 const customer={id:700,name:'Same Name',phone:'03001111111'};
 const other={id:701,name:'Same Name',phone:'03002222222'};
 const saved={id:800,customer_id:700,customer,garment_type:'Shirt',tailor:'Unassigned',unit:'in',length:'40.25',notes:'Existing notes'};
 w.MEASUREMENT_CONFIG.required.forEach(f=>saved[f]='10');
 w.allCustomers=[customer,other];w.savedMeasurementSets=[saved,{...saved,id:801,garment_type:'Trouser'}];
 w.openModal('add-measurement',null);
 assert.match(w.document.getElementById('modal-content').textContent,/No order required/);
 w.selectCustomer(700);
 assert.equal(w.document.getElementById('meas-garment').value,'Shirt');
 assert.equal(w.document.querySelectorAll('#meas-garment optgroup').length,0);
 assert.deepEqual(Array.from(w.document.getElementById('meas-saved').options,o=>o.value),['new','saved:800']);
 assert.equal(w.savedMeasurementsForGarment(700,' shirt ')[0].id,800);
 assert.equal(w.savedMeasurementsForGarment(701,'Shirt').length,0);
 assert.equal(w.document.getElementById('meas-tailor').type,'hidden');
 assert.doesNotMatch(w.document.getElementById('meas-garment').textContent,/saved:|Update saved|New measurements/);
 w.selectGarmentMeasurements('Trouser');
 assert.equal(w.document.getElementById('meas-saved').value,'saved:801');
 assert.deepEqual(Array.from(w.document.getElementById('meas-saved').options,o=>o.value),['new','saved:801']);
 w.selectMeasurementSet('saved:800');
 assert.equal(w.document.getElementById('meas-garment').value,'Trouser');
 assert.equal(w.document.getElementById('meas-saved').value,'saved:801');
 w.selectGarmentMeasurements('No saved category');
 assert.deepEqual(Array.from(w.document.getElementById('meas-saved').options,o=>o.value),['new']);
 assert.equal(w.document.getElementById('meas-length').value,'');
 w.selectGarmentMeasurements('Shirt');
 assert.equal(w.document.getElementById('meas-length').value,'40.25');
 assert.equal(w.document.getElementById('meas-unit').value,'in');
 assert.equal(w.document.getElementById('meas-customer').dataset.customerId,'700');
 let request;w.Atelier.api.put=async(url,payload)=>{request={url,payload};return {measurement:{...saved,...payload},message:'Updated'};};
 w.document.getElementById('meas-length').value='41.5';
 await w.saveMeasurement(800);
 assert.equal(request.url,'/measurements/800');assert.equal(request.payload.customer_id,700);assert.equal(request.payload.length,'41.5');assert.equal(request.payload.garment_type,'Shirt');
 assert.equal(w.savedMeasurementSets.length,2);
 w.selectCustomer(700);w.selectMeasurementSet('saved:800');
 assert.equal(w.document.getElementById('meas-length').value,'41.5');
 w.selectMeasurementSet('new');
 assert.equal(w.document.getElementById('meas-length').value,'');
 assert.match(w.document.getElementById('save-measurement-btn').getAttribute('onclick'),/null/);
 w.selectMeasurementSet('saved:800');
 w.document.getElementById('meas-customer').value='Different';w.measurementCustomerChanged();
 assert.equal(w.document.getElementById('meas-customer').dataset.customerId,'');
 assert.equal(w.document.getElementById('meas-length').value,'');
 assert.match(w.document.getElementById('save-measurement-btn').getAttribute('onclick'),/null/);
 w.openModal('print-preview');
 assert.equal(w.document.getElementById('measurement-print-choice').options.length,2);
 w.openModal('view-measurement',saved);
 assert.match(w.document.getElementById('modal-content').textContent,/Fields Filled/);
 assert.doesNotMatch(w.document.getElementById('modal-content').textContent,/Completed/);
 assert.doesNotMatch(w.document.body.textContent,/ORD-2454|Sneha Reddy|Page 129/);
 assert.deepEqual(errors,[]);
 console.log('PASS: saved-set selection, autofill, same-record PUT, exact customer ID, repeat edit, separate new set, safe customer switch.');
}catch(e){console.error(e);process.exitCode=1;}finally{dom.window.close();}});
