const fs=require('fs'),path=require('path'),{chromium}=require('playwright');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
const html=fs.readFileSync('dev/artifacts/mixed-orders-browser.html','utf8');
await page.route('**/*',async route=>{const u=new URL(route.request().url());if(u.pathname==='/'){return route.fulfill({contentType:'text/html',body:html})}const asset=path.resolve('public','.'+u.pathname);if(asset.startsWith(path.resolve('public')+path.sep)&&fs.existsSync(asset)&&fs.statSync(asset).isFile())return route.fulfill({path:asset});if(route.request().resourceType()==='fetch')return route.fulfill({contentType:'application/json',body:JSON.stringify({success:true,orders:[],counts:{},notifications:[]})});return route.abort();});
await page.goto('http://127.0.0.1/');await page.waitForTimeout(1500);

page.on('dialog',d=>d.accept());
const modal=page.locator('#modal-content');
await page.getByRole('button',{name:/Create Order/}).click({timeout:5000});
await modal.locator('select').selectOption({index:1});
const ids=await page.evaluate(()=>({garment:activeServices.find(p=>p.profile.key==='generic').id,accessory:activeServices.find(p=>p.profile.key==='accessory').id}));
await modal.locator('select').first().selectOption(String(ids.garment));
await modal.getByLabel('Quantity',{exact:true}).fill('2');await modal.getByLabel('Quantity',{exact:true}).dispatchEvent('change');
await modal.getByRole('button',{name:'+ Add garment',exact:true}).click();
await modal.locator('select').last().selectOption(String(ids.accessory));
await modal.getByRole('button',{name:'Next',exact:true}).click();
const required=await page.evaluate(()=>rowProfile(newOrderState.garments[0]).required);
for(const key of required) await modal.locator(`input[oninput="itemMeasure('${key}',this.value)"]`).fill('40');
await page.evaluate(()=>itemTab(0,1));
await modal.getByLabel('Copy another piece').selectOption('0:0');
await modal.getByLabel(/^Unit/).selectOption('cm');
await page.evaluate(()=>itemTab(0,0));
let state=await page.evaluate(()=>newOrderState.garments);
if(state[0].pieces[0].unit!=='in'||state[0].pieces[1].unit!=='cm'||state[0].pieces[0].values.length!=='40') throw Error('Piece units/values were not independent');
await modal.getByRole('button',{name:'Back',exact:true}).click();
await modal.getByLabel('Quantity',{exact:true}).first().fill('1');await modal.getByLabel('Quantity',{exact:true}).first().dispatchEvent('change');
await modal.getByLabel('Quantity',{exact:true}).first().fill('2');await modal.getByLabel('Quantity',{exact:true}).first().dispatchEvent('change');
state=await page.evaluate(()=>newOrderState.garments);
if(Object.keys(state[0].pieces[1].values).length) throw Error('New piece inherited removed values');
await modal.getByRole('button',{name:'Next',exact:true}).click();
await page.evaluate(()=>itemTab(0,1));await modal.getByLabel('Copy another piece').selectOption('0:0');
await modal.getByRole('button',{name:'Next',exact:true}).click();
await modal.getByLabel('Delivery date').fill('2026-09-20');
await modal.getByRole('button',{name:'Next',exact:true}).click();
await page.screenshot({path:'dev/artifacts/mixed-wizard-confirm.png'});
await page.evaluate(()=>{closeModal();openModal('edit-order',orders.find(o=>o.garments.length===2));});
await modal.getByRole('button',{name:'Next',exact:true}).click();
state=await page.evaluate(()=>newOrderState.garments);
if(!state[0].pieces[0].id) throw Error('Edit lost piece ID');
await page.screenshot({path:'dev/artifacts/mixed-wizard-edit.png'});
console.log('PASS: create, mixed rows, per-piece copy, independent units, quantity shrink/grow, back navigation, confirmation and edit IDs');
console.log('Browser errors:',errors);
await browser.close();if(errors.length)process.exit(1);
})().catch(e=>{console.error(e);process.exit(1)});
